### ISSUE TITLE
Discord invitation link is not available

### ISSUE THREAD

**Issue by luckyfrog1** [Tuanzi1015/open-assistant-api#20]
<img width="650" alt="image" src="https://github.com/Tuanzi1015/open-assistant-api/assets/33177790/d811fc6e-2ca4-4140-9170-5c694b50ff5f">
I tried to join the discord channel to communicate with other members but it didn't work, did the invite expire or do I need to provide any information?

**Comment by liuooo** [comment]
try this link, https://discord.gg/3Yw3XVyH
