### ISSUE TITLE
Typos in thread_runner.py & run.py

### ISSUE THREAD

**Issue by lml2468** [Tuanzi1015/open-assistant-api#5]
thread_runner.py: `submit_tool_ouputs_to_run` -> `submit_tool_outputs_to_run`
run.py: `tool_call_outpus` -> `tool_call_outputs`

**Comment by kense-lab** [comment]
https://github.com/Tuanzi1015/open-assistant-api/blob/59b95db7466d37d5d651a4370bc164db81d4e4aa/app/api/v1/runs.py#L139
